specfile_path: vesktop.spec

upstream_package_name: vesktop
downstream_package_name: vesktop

sync_changelog: true

# The key is to nest all package-specific configuration under 'packages'
packages:
  vesktop:
    # --- ADD THIS BLOCK ---
    spec_template:
      # This ensures %__version gets set correctly from the Git tag/release name
      __version: '%(echo $PACKIT_PROJECT_VERSION)'
    # ----------------------
    actions:
      # Use the YAML literal block scalar (the pipe |) for the multi-line script.
      post_upstream_clone: |
        # Use the version defined in the SPEC file
        VERSION=$(grep -m1 '^Version:' vesktop.spec | awk '{print $2}');
        echo "Detected version: $VERSION";
        echo "Downloading tarball...";
        wget -O vesktop-$VERSION.tar.gz \
        https://github.com/Vencord/Vesktop/releases/download/v$VERSION/vesktop-$VERSION.tar.gz;
        echo "Contents:";
        ls -lh

# srpm_build_deps must be at the top level, or under 'packages: vesktop' (I'm keeping it simple here)
srpm_build_deps:
  - wget

jobs:
  - job: copr_build
    trigger: release # Automatic builds on upstream release
    owner: "ackerman"
    project: vesktop
    targets:
      - fedora-rawhide-x86_64
      - fedora-43-x86_64
      - fedora-42-x86_64

  - job: copr_build
    trigger: pull_request
    owner: "ackerman"
    project: vesktop
    targets:
      - fedora-rawhide-x86_64
