specfile_path: vesktop.spec

upstream_package_name: vesktop
downstream_package_name: vesktop

sync_changelog: true

actions:
  # Packit needs the actual source tarball since Vesktop is not built from “git source”
  post_upstream_clone: |
    VERSION=$(grep Version vesktop.spec | awk '{print $2}')
    wget -O "vesktop-$VERSION.tar.gz" \
      "https://github.com/Vencord/Vesktop/releases/download/v$VERSION/vesktop-$VERSION.tar.gz"
    ls -lh

jobs:
  - job: copr_build
    trigger: release
    owner: "ackerman"
    project: vesktop
    targets:
      - fedora-rawhide
      - fedora-43
      - fedora-42

  - job: copr_build
    trigger: pull_request
    owner: "ackerman"
    project: vesktop
    allowed_pr_authors:
      - "@packit"
      - "ackerman"
    targets:
      - fedora-rawhide

