upstream_project_url: https://github.com/Vencord/Vesktop
specfile_path: vesktop.spec

jobs:
  - job: copr_build
    trigger: release
    targets:
      - fedora-42-x86_66
      - fedora-rawhide-x86_64
      - fedora-43-x86_64
