specfile_path: vesktop.spec

upstream_package_name: vesktop
downstream_package_name: vesktop


sync_changelog: true

jobs:
  - job: copr_build
    trigger: release
    targets:
      - fedora-rawhide-x86_64
      - fedora-42-x86_64  
      - fedora-43-x86_64
    owner: "@ackerman"
    project: vesktop


  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide-x86_64

# Actions to perform
actions:
  - action: fix-spec-file
    event: pull_request

  - action: sync-from-downstream
    event: pull_request
