specfile_path: vesktop.spec

upstream_package_name: vesktop
downstream_package_name: vesktop

sync_changelog: true

srpm_build_deps:
  - wget

actions:
  post-upstream-clone: |
    VERSION=$(grep -m1 '^Version:' vesktop.spec | awk '{print $2}')
    echo "Detected version: $VERSION"

    echo "Downloading tarball..."
    wget -O "vesktop-$VERSION.tar.gz" \
      "https://github.com/Vencord/Vesktop/releases/download/v$VERSION/vesktop-$VERSION.tar.gz"

    echo "Contents:"
    ls -lh

jobs:
  - job: copr_build
    trigger: release
    owner: "ackerman"
    project: vesktop
    targets:
      - fedora-rawhide
      - fedora-43
      - fedora-42

  - job: copr_build
    trigger: pull_request
    owner: "ackerman"
    project: vesktop
    allowed_pr_authors:
      - "@packit"
      - "ackerman"
    targets:
      - fedora-rawhide

