specfile_path: vesktop.spec

upstream_package_name: vesktop
downstream_package_name: vesktop

jobs:
  - job: copr_build
    trigger: release
    targets:
      - fedora-rawhide-x86_64
      - fedora-42-x86_64
      - fedora-43-x86_64
    owner: ackerman
    project: vesktop
    specfile_path: vesktop.spec
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - main
